"""
Pydantic schemas for DQ Recommender Agent.

Defines data models for rule definitions, generation requests/responses,
and related types used throughout the DQ recommendation workflow.
"""

from enum import Enum
from typing import Optional, List
from datetime import datetime
from pydantic import BaseModel, Field


class RuleType(str, Enum):
    """Types of data quality rules."""
    COMPLETENESS = "completeness"
    UNIQUENESS = "uniqueness"
    RANGE = "range"
    PATTERN = "pattern"
    FRESHNESS = "freshness"
    REFERENTIAL = "referential"
    CUSTOM = "custom"


class Severity(str, Enum):
    """Severity levels for data quality rules."""
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


class RuleStatus(str, Enum):
    """Lifecycle status of a data quality rule."""
    PENDING = "pending"
    APPROVED = "approved"
    ACTIVE = "active"
    DISABLED = "disabled"
    DEPRECATED = "deprecated"


class DQRule(BaseModel):
    """
    Data Quality Rule definition.

    Represents a single rule that can be applied to validate data quality.
    Rules can be generated by AI, derived from templates, or created manually.
    """
    id: Optional[str] = Field(None, description="Rule UUID")
    dataset_id: str = Field(..., description="Dataset this rule applies to")
    column_name: Optional[str] = Field(
        None,
        description="Column this rule applies to (null for table-level rules)"
    )
    rule_type: RuleType = Field(..., description="Type of quality rule")
    dqdl_expression: str = Field(..., description="DQDL rule expression")
    description: str = Field(..., description="Human-readable rule description")
    reasoning: Optional[str] = Field(
        None,
        description="AI-provided reasoning for why this rule is appropriate"
    )
    severity: Severity = Field(default=Severity.WARNING, description="Rule severity")
    status: RuleStatus = Field(default=RuleStatus.PENDING, description="Rule status")
    template_name: Optional[str] = Field(
        None,
        description="Template name if rule was generated from a template"
    )
    generated_by: Optional[str] = Field(
        None,
        description="Generation source: ai_recommender, glue_ml, user, template"
    )
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class RuleGenerationRequest(BaseModel):
    """
    Request for generating a data quality rule from natural language.

    Used by the rule_generator tool to create DQDL rules from user descriptions.
    """
    description: str = Field(
        ...,
        description="Natural language description of the quality rule"
    )
    column_name: str = Field(
        ...,
        description="Column to apply the rule to"
    )
    profile_summary: dict = Field(
        ...,
        description="Profile statistics for the column (from profiler agent)"
    )


class RuleGenerationResponse(BaseModel):
    """
    Response from rule generation containing the DQDL rule and metadata.

    The AI provides not just the rule but also reasoning and potential issues.
    """
    rule: str = Field(..., description="Generated DQDL rule expression")
    reasoning: str = Field(
        ...,
        description="Explanation of why this rule is appropriate"
    )
    false_positive_scenarios: List[str] = Field(
        default_factory=list,
        description="Scenarios where the rule might incorrectly flag valid data"
    )
    severity: Severity = Field(
        default=Severity.WARNING,
        description="Recommended severity level"
    )


class TemplateParameter(BaseModel):
    """Parameter definition for a rule template."""
    name: str = Field(..., description="Parameter name")
    type: str = Field(..., description="Parameter type: string, number, boolean")
    required: bool = Field(default=False, description="Whether parameter is required")
    default: Optional[str] = Field(None, description="Default value")
    description: Optional[str] = Field(None, description="Parameter description")


class RuleTemplate(BaseModel):
    """
    Pre-defined rule template for common data quality patterns.

    Templates allow applying industry-standard rules without AI generation.
    """
    name: str = Field(..., description="Template name")
    category: str = Field(
        ...,
        description="Category: format, range, consistency, compliance"
    )
    description: str = Field(..., description="Template description")
    dqdl_pattern: str = Field(
        ...,
        description="DQDL pattern with {column} and parameter placeholders"
    )
    parameters: List[TemplateParameter] = Field(
        default_factory=list,
        description="Required and optional parameters"
    )
    industry_standards: List[str] = Field(
        default_factory=list,
        description="Related standards: HIPAA, PCI-DSS, GDPR, etc."
    )


class RemediationSuggestion(BaseModel):
    """Suggestion for remediating a data quality issue."""
    issue_type: str = Field(..., description="Type of issue being remediated")
    column: str = Field(..., description="Affected column")
    suggestions: List[str] = Field(
        ...,
        description="List of remediation actions"
    )
    priority: str = Field(
        default="medium",
        description="Remediation priority: high, medium, low"
    )


class GlueRecommendation(BaseModel):
    """Response from AWS Glue Data Quality recommendations."""
    run_id: str = Field(..., description="Glue recommendation run ID")
    ruleset: Optional[str] = Field(
        None,
        description="Generated DQDL ruleset"
    )
    status: str = Field(..., description="Run status")
    error: Optional[str] = Field(None, description="Error message if failed")
